### ISSUE TITLE
Failed to parsing TokyoToshokan Traceback: Traceback (most recent call last)

### ISSUE THREAD

**Issue by The-Drake** [gborri/Sick-Beard#12]
2014-09-21 19:15:58 SEARCHQUEUE-DOWNLOADABLE_SEARCH-72454 :: [TokyoToshokan] :: Failed to parsing TokyoToshokan Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/tokyotoshokan.py", line 108, in _doSearch
    if torrent_rows[0].find('td', attrs={'class': 'centertext'}):
IndexError: list index out of range

2014-09-21 19:15:58 SEARCHQUEUE-DOWNLOADABLE_SEARCH-72454 :: Failed to parsing TokyoToshokan Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/tokyotoshokan.py", line 108, in _doSearch
    if torrent_rows[0].find('td', attrs={'class': 'centertext'}):
IndexError: list index out of range

2014-09-21 19:15:58 SEARCHQUEUE-DOWNLOADABLE_SEARCH-72454 :: Failed to parsing TokyoToshokan Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/tokyotoshokan.py", line 108, in _doSearch
    if torrent_rows[0].find('td', attrs={'class': 'centertext'}):
IndexError: list index out of range

2014-09-21 19:15:54 SEARCHQUEUE-DOWNLOADABLE_SEARCH-72454 :: [TokyoToshokan] :: Failed to parsing TokyoToshokan Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/tokyotoshokan.py", line 108, in _doSearch
    if torrent_rows[0].find('td', attrs={'class': 'centertext'}):
IndexError: list index out of range

**Comment by gborri** [comment]
It's not my plugin we have to wait util fixed in echel0n fork. Probably on
next merge will be fixed.
