### ISSUE TITLE
Cannot operate on a closed database

### ISSUE THREAD

**Issue by ToRvaLDz** [gborri/Sick-Beard#8]
After pulling the latest version:

2014-07-18 10:43:50 ERROR    BACKLOG :: DB error: no such table: scene_exceptions_refresh
2014-07-18 10:43:50 ERROR    BACKLOG :: Fatal error executing query: Cannot operate on a closed database.
2014-07-18 10:43:50 ERROR    BACKLOG :: Exception generated in thread BACKLOG: Cannot operate on a closed database.
2014-07-18 10:43:50 DEBUG    BACKLOG :: 'Traceback (most recent call last):\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\scheduler.py", line 91, in runAction\n    self.action.run(self.force)\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\searchBacklog.py", line 194, in run\n    self.searchBacklog()\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\searchBacklog.py", line 108, in searchBacklog\n    sickbeard.searchQueueScheduler.action.add_item(backlog_queue_item)  #@UndefinedVariable\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\search_queue.py", line 98, in add_item\n    sickbeard.name_cache.buildNameCache()\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\name_cache.py", line 100, in buildNameCache\n    sickbeard.scene_exceptions.retrieve_exceptions()\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\scene_exceptions.py", line 164, in retrieve_exceptions\n    if setLastRefresh(\'normal\'):\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\scene_exceptions.py", line 48, in setLastRefresh\n    [list, time.time()])\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\db.py", line 188, in action\n    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)\n  File "C:\Users\ToRvaLDs\SickBeard\sickbeard\db.py", line 94, in execute\n    cursor.close()\nProgrammingError: Cannot operate on a closed database.\n'

**Comment by gborri** [comment]
remove cache.db file and restsart.

**Comment by ToRvaLDz** [comment]
Deleted cache.db and restarted same error, I think the db is not upgraded:

2014-07-18 19:22:02 DAILYSEARCHER :: DB error: no such table: scene_exceptions_refresh
2014-07-18 19:22:02 DAILYSEARCHER :: Fatal error executing query: Cannot operate on a closed database.

**Comment by gborri** [comment]
Please, send me your db.

Giovanni
Il 18/lug/2014 19:33 "ToRvaLDz" notifications@github.com ha scritto:

**Comment by ToRvaLDz** [comment]
You can download it here:

https://docs.google.com/file/d/0B2OCmE6PdaVua2RhRG1tSFRFY28/edit?usp=docslist_api

**Comment by The-Drake** [comment]
FYI: same error here.

After upgrading, deleting cache.db, restarted several times, this is my log error:

2014-07-20 17:12:09 BACKLOG :: DB error: no such table: scene_exceptions_refresh
2014-07-20 17:12:09 BACKLOG :: Fatal error executing query: Cannot operate on a closed database.
2014-07-20 17:12:09 BACKLOG :: Exception generated in thread BACKLOG: Cannot operate on a closed database.
2014-07-20 17:11:57 DOWNLOADABLE_SEARCH :: DB error: no such table: scene_exceptions_refresh
2014-07-20 17:11:57 DOWNLOADABLE_SEARCH :: Fatal error executing query: Cannot operate on a closed database.
2014-07-20 17:11:57 DOWNLOADABLE_SEARCH :: Exception generated in thread DOWNLOADABLE_SEARCH: Cannot operate on a closed database.
2014-07-20 17:11:54 MAIN :: DB error: no such table: scene_exceptions_refresh
2014-07-20 17:11:54 MAIN :: Fatal error executing query: Cannot operate on a closed database.

**Comment by gborri** [comment]
i need cache.db not sickbeard.db

**Comment by gborri** [comment]
send me also the log part on which the db is migrated...

**Comment by ToRvaLDz** [comment]
Check here:

https://drive.google.com/file/d/0B2OCmE6PdaVud1lZbVdVWHIwcDg/edit?usp=sharing

**Comment by gborri** [comment]
update sb. delete cache.db ad restart

**Comment by ToRvaLDz** [comment]
The missing tables has been created, now seems ok.

Thank you!
